### PR TITLE
Pearson Correlation detector

### PR DESCRIPTION
**Pull request by AlphaGit**
Background
-----

These changes are made to detect linear correlations and deviations from the correlations detected in the training ("regular") data. In order to do that, this uses the Pearson Correlation measure, which you can read about in here: https://statistics.laerd.com/spss-tutorials/pearsons-product-moment-correlation-using-spss-statistics.php

Changes
----

- Added `pandas` to the environment
- Added `LinearPearsonAnomalyDetector` and its tests
- Added VS Workspace file (it was accidental, but I think we might benefit from it anyway, so I left it)

Notes
----

- I don't fully like the idea of detecting if the model is suitable with a threshold and then using another one for evaluation. Thoughts on that?

### CODE REVIEW

**Comment by rochimensi** [comment]
From a Machine Learning perspective, for Supervised learning techniques, we train, then we evaluate. No additional phases.

To answer your question about the different thresholds, I observed that `is_model_suitable` could be the detector training function, taking any model. Then we could have a quality metric that represents the Detector function confidence. Maybe the threshold is this quality metric we need to take a model seriously or not :D

**Comment by AlphaGit** [comment]
Added bbe9dc0138a8ff2c5c6edfca7c4396daed69add8, only with new tests. This covers the special cases considered in https://trello.com/c/vp1zs8bx, which were (unknowingly) covered by me in this first implementation.

**Comment by AlphaGit** [comment]
Closing -- I'll adapt based on @rochimensi's suggestion but that will make a change in the general structure. I'll open a new PR when that's ready.

**Comment by AlphaGit** [comment]
Changes done in #7.

**Pull request closed without merging**
